postgres_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: valerian
      port: 5432
      dbname: postgres
      schema: data_warehouse
      threads: 1
